language: node_js
node_js:
  - 0.12
env:
  - NODE_ENV=production_testing
before_script:
  - export DISPLAY=:99.0
  - npm install -g gulp
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - sleep 2 #give server time to start
script: 
  - npm run test-frontend
  - npm run test-backend
  - npm run test-e2e