language: node_js
node_js:
  - 0.12
before_script:
  - export DISPLAY=:99.0
  - npm start
  - npm install -g gulp
  - npm run webdriver-update
  - sleep 1 #give server time to start
script: 
  - npm run test-frontend
  - npm run test-backend