language: node_js
node_js:
  - 0.12
env:
  - NODE_ENV=test
before_script:
  - export DISPLAY=:99.0
  - npm install -g gulp
  - sleep 1 #give server time to start
script: 
  - npm run test-frontend
  - npm run test-backend